# Generated by Django 3.1.7 on 2021-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article Title', max_length=120)),
                ('content', models.TextField(default='Enter Content')),
                ('author', models.CharField(default='Chan', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
