# Generated by Django 3.1.7 on 2021-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPostApp', '0002_auto_20210413_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='blogPostApp/static'),
        ),
    ]
