# Generated by Django 3.1.7 on 2021-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPostApp', '0006_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(default='Tutorial Title', max_length=120),
        ),
    ]
