# Generated by Django 3.1.7 on 2021-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPostApp', '0009_auto_20210414_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='course',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogPostApp/static'),
        ),
    ]
