# Generated by Django 3.1.7 on 2021-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPostApp', '0011_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('Unity', 'Unity'), ('Web', 'Web'), ('Blockchain', 'Blockchain'), ('General', 'General'), ('DesignPatterns', 'DesignPatterns'), ('Programming', 'Programming')], default='', max_length=120),
        ),
    ]
